---
- name: "Add Jenkins GPG key"
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

- name: "Adding Jenkins to apt repository"
  shell: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null


- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install Jenkins"
  apt:
    name: jenkins
    state: present
  notify: Restart Jenkins
