---
- name: "Playbook to install jenkins on server"
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: "Check the OS details"
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

    - name: "Server update and upgrade"
      apt:
        update_cache: yes
        upgrade: yes  # Optional, if you intend to upgrade packages

    - name: "Install Java-jdk"
      apt:
        name: openjdk-17-jdk
        state: present

    - name: "Check Java version"
      command: java -version
      register: java_version_output

    - name: "Java version output"
      debug:
        var: java_version_output.stderr_lines

    - name: "Add Jenkins GPG key"
      shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: "Adding Jenkins to apt repository"
      shell: echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null


    - name: "Update apt cache"
      apt:
        update_cache: yes

    - name: "Install Jenkins"
      apt:
        name: jenkins
        state: present

    - name: "Start and enable jenkins"
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: "Get Jenkins Administrator Password"
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Show the Jenkins Admin Password
      debug:
        msg: "Jenkins Admin Password: {{ jenkins_admin_password.stdout }}"






